# RESHAPE

In [1]:
import numpy as np

# Split

In [2]:
l = [1,2,3,4,5,6,7,8,9]

In [6]:
np.split(l,[3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([8, 9])]

# Splitin değerini birden çok değişkene eşitleme

In [7]:
x, y, z = np.split(l,[3,7])

In [8]:
print(x)
print(y)
print(z)

[1 2 3]
[4 5 6 7]
[8 9]


# Vsplit

In [9]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [10]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [12]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# hsplit

In [13]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]