# Conditional Indexing

In [27]:
import numpy as np

In [30]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [32]:
a[a<5]

array([1, 2, 3, 4])

In [38]:
filt = a < 3

In [35]:
a[filt]

array([1, 2])

In [39]:
b = np.array([2,2,3,25,84,65,7,24,9])

In [40]:
a == b

array([False,  True,  True, False, False, False,  True, False,  True])

In [41]:
a[a==b]

array([2, 3, 7, 9])

In [42]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [43]:
(a > 2) & (a < 5)

array([False, False,  True,  True, False, False, False, False, False])

In [44]:
a[(a > 2) & (a < 5)]

array([3, 4])

# Filtrenin Değili   ~~

In [46]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
filt = a < 5
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [48]:
a[filt]

array([1, 2, 3, 4])

In [49]:
a[not((a > 5) & (a < 9))]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [50]:
a[~((a > 5) & (a < 9))]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
a=np.arange(-5,3).reshape(2,4)

In [52]:
a

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2]])