In [1]:
import numpy as np

In [3]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
np.sum(a)

210

In [5]:
filt = a < 5

In [7]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [6]:
np.sum(a[filt])

10

In [12]:
filt = (a > 5) & (a < 9)

In [16]:
np.sum(filt)

3

In [13]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [14]:
a[filt]

array([6, 7, 8])

In [15]:
np.sum(a[filt])

21

In [17]:
np.sum(a[~((a > 5) & (a < 9))])

189

#  Belirli axis üzerinde toplama

In [18]:
np.sum(a, axis =0)

array([34, 38, 42, 46, 50])

In [19]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

In [20]:
np.sum(a, axis =0).shape

(5,)

#  HackerRank Challange 

In [21]:
import numpy as np

n, m = map(int, input().split())

array = [list(map(int, input().split())) for _ in range(n)]

b = np.sum(array, axis = 0) 

result = np.prod(b)  

print(result)


2 2
1 3
4 2
25
