# Identity Matrix

In [1]:
import numpy as np

In [2]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [3]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Operations

In [4]:
[2,4,6] * 3

[2, 4, 6, 2, 4, 6, 2, 4, 6]

In [5]:
[2,4,6] + [2,4,6] + [2,4,6]

[2, 4, 6, 2, 4, 6, 2, 4, 6]

In [6]:
x = np.array([1,2,3])
y = np.array([2,4,6])

x*y

array([ 2,  8, 18])

In [7]:
x+y

array([3, 6, 9])

In [8]:
x = x*3
x

array([3, 6, 9])