# Concatenata

In [1]:
import numpy as np

In [31]:
# Read n, m, p
n, m, p = map(int, input().split())

# Read first array (n rows)
array1 = [list(map(int, input().split())) for _ in range(n)]

# Read second array (m rows)
array2 = [list(map(int, input().split())) for _ in range(m)]

# Convert to numpy arrays
A = np.array(array1)
B = np.array(array2)

# Concatenate along axis 0
result = np.concatenate((A, B), axis=0)

# Print result
print(result)


4 3 2
2 4
1 3
4 8
5 2
1 2
2 5
4 5
[[2 4]
 [1 3]
 [4 8]
 [5 2]
 [1 2]
 [2 5]
 [4 5]]


# Stack

In [36]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [37]:
b = np.array([5,6,7,8])

In [38]:
a.shape

(4,)

In [39]:
b.shape

(4,)

In [40]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
np.stack([a,b]).shape

(2, 4)

In [42]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [43]:
np.stack([a,b], axis =1).shape

(4, 2)

In [45]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.concatenate((a,b), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1