In [1]:
import numpy as np

In [3]:
x=np.array(["4"],dtype="int32") 

In [4]:
x

array([4])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
x=np.zeros([3,8,8,5])

In [11]:
np.full((2,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [12]:
np.full((4,5), "a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [13]:
np.full((4,5), 5.2, dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [14]:
np.full((4,5),5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(12,7,-2)

array([12, 10,  8])

In [19]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [24]:
np.linspace(1,2, num=7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [25]:
np.linspace(1.4,4.8,3)

array([1.4, 3.1, 4.8])