In [1]:
import numpy as np

# ARRAY ATTRIBUTE

In [3]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
y = np.zeros((3,4,5))
print(y)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [5]:
x.shape

(2, 3)

In [6]:
y.shape

(3, 4, 5)

# ndim (ka. boyutlu olduğunu verir) 

In [7]:
x.ndim

2

In [9]:
y.ndim

3

# Size kaç elemanlı olduğunu döndürür!!

In [10]:
x.size

6

In [11]:
y.size

60

# dtype

In [12]:
x.dtype

dtype('float64')

In [13]:
y.dtype

dtype('float64')