# RESHAPE

In [1]:
import numpy as np

In [11]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a.ndim

1

In [13]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
b = a.reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
b.ndim

2

a.reshape(-1,2) = a.reshape(5,2)  çünkü -1 oto hesaplama yapar

In [19]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Yeni Boyut Eklemek

In [20]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
a[np.newaxis, :].shape

(1, 10)

In [24]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [26]:
a[:, np.newaxis].shape

(10, 1)

In [27]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [28]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])